---
broadway304a:
  :host: broadway304a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
butler209a:
  :host: butler209a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Butler
  :double_sided: true
butler209b:
  :host: butler209b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Butler
  :double_sided: true
butler213a:
  :host: butler213a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Butler
  :double_sided: true
butler213b:
  :host: butler213b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Butler
  :double_sided: true
butler213c:
  :host: butler213c-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Butler
  :double_sided: true
butler300a:
  :host: butler300a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Butler
  :double_sided: true
butler300b:
  :host: butler300b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Butler
  :double_sided: true
butler403a:
  :host: butler403a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Butler
  :double_sided: true
carlton100a:
  :host: carlton100a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
carlton100b:
  :host: carlton100b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
carman103b:
  :host: carman103b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
claremntb01a:
  :host: claremntb01a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
ec10a:
  :host: ec10a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 Series PS
  :location: Residence Halls
  :double_sided: true
ec18a:
  :host: ec18a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 Series PS
  :location: Residence Halls
  :double_sided: true
et251color:
  :host: et251color-ninja.atg.columbia.edu
  :driver: HP Color LaserJet 4700 PS
  :location: Mudd
  :double_sided: true
furnald107a:
  :host: furnald107a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
harmony100a:
  :host: harmony100a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
hartley111a:
  :host: hartley111a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
hartley111b:
  :host: hartley111b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
iab323color:
  :host: iab323color-ninja.atg.columbia.edu
  :driver: HP Color LaserJet 5500 PS
  :location: International Affairs
  :double_sided: true
iab323a:
  :host: iab323a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: International Affairs
  :double_sided: true
iab323b:
  :host: iab323b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: International Affairs
  :double_sided: true
iab509a:
  :host: iab509a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: International Affairs
  :double_sided: true
lerner200a:
  :host: lerner200a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Lerner
  :double_sided: true
lerner200b:
  :host: lerner200b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Lerner
  :double_sided: true
lerner300a:
  :host: lerner300a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Lerner
  :double_sided: true
lerner300b:
  :host: lerner300b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Lerner
  :double_sided: true
lewisohn300a:
  :host: lewisohn300a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Lewisohn
  :double_sided: true
lewisohn300b:
  :host: lewisohn300b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Lewisohn
  :double_sided: true
mcbain100a:
  :host: mcbain100a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
et251a:
  :host: et251a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Mudd
  :double_sided: true
et251b:
  :host: et251b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Mudd
  :double_sided: true
et251c:
  :host: et251c-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Mudd
  :double_sided: true
mudd422a:
  :host: mudd422a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Mudd
  :double_sided: true
mudd422b:
  :host: mudd422b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Mudd
  :double_sided: true
riverb01a:
  :host: riverb01a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
ruggles100a:
  :host: ruggles100a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
russell100a:
  :host: russell100a-ninja.tc.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Teachers College
  :double_sided: true
schapiro108a:
  :host: schapiro108a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
schermerhorn558a:
  :host: schermerhorn558a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Schermerhorn
  :double_sided: true
six00w113a:
  :host: six00w113a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
stat902a:
  :host: stat902a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Statistics
  :double_sided: true
watt100a:
  :host: watt100a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
wien211a:
  :host: wien211a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
wien211b:
  :host: wien211b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
woodbridge100a:
  :host: woodbridge100a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Residence Halls
  :double_sided: true
bclibrary100a:
  :host: bclibrary100a-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
bclibrary200a:
  :host: bclibrary200a-ninja.barnard.edu
  :driver: HP LaserJet 9050 Series PS
  :location: Barnard
  :double_sided: true
brooks100a:
  :host: brooks100a-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
brooks100b:
  :host: brooks100b-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
dcc413a:
  :host: dcc413a-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
dcc413b:
  :host: dcc413b-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
diana307a:
  :host: diana307a-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
diana307b:
  :host: diana307b-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
diana307c:
  :host: diana307c-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
lehman018a:
  :host: lehman018a-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
plimpton100a:
  :host: plimpton100a-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
plimpton100b:
  :host: plimpton100b-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
sixsixteen100a:
  :host: sixsixteen100a-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
sixsixteen100b:
  :host: sixsixteen100b-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
sulzberger100a:
  :host: sulzberger100a-ninja.barnard.edu
  :driver: HP LaserJet 9050 PS
  :location: Barnard
  :double_sided: true
avery200a:
  :host: avery200a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4015
  :location: Avery
  :double_sided: true
avery200b:
  :host: avery200b-ninja.atg.columbia.edu
  :driver: HP LaserJet P4015
  :location: Avery
  :double_sided: true
burke100a:
  :host: burke100a-ninja.atg.columbia.edu
  :driver: HP LaserJet 4300 Series PS
  :location: Burke
  :double_sided: true
burke300a:
  :host: burke300a-ninja.atg.columbia.edu
  :driver: HP LaserJet 4350 Series PS
  :location: Burke
  :double_sided: true
butler305a:
  :host: butler305a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Butler
  :double_sided: true
butler401a:
  :host: butler401a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Butler
  :double_sided: true
butler501a:
  :host: butler501a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Butler
  :double_sided: true
butler606a:
  :host: butler606a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Butler
  :double_sided: true
dodgeart701a:
  :host: dodgeart701a-ninja.atg.columbia.edu
  :driver: HP LaserJet 5100 PS
  :location: Dodge
  :double_sided: true
dodgeart701b:
  :host: dodgeart701b-ninja.atg.columbia.edu
  :driver: HP LaserJet 5200 PS
  :location: Dodge
  :double_sided: true
iab215a:
  :host: iab215a-ninja.atg.columbia.edu
  :driver: HP LaserJet 4200 PS
  :location: International Affairs
  :double_sided: true
iab310a:
  :host: iab310a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: International Affairs
  :double_sided: true
kent300a:
  :host: kent300a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4015
  :location: Kent
  :double_sided: true
kent300b:
  :host: kent300b-ninja.atg.columbia.edu
  :driver: HP LaserJet P4015
  :location: Kent
  :double_sided: true
math303a:
  :host: math303a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Math
  :double_sided: true
nwcb400a:
  :host: nwcb400a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Northwest Corner Building
  :double_sided: true
nwcb400b:
  :host: nwcb400b-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Northwest Corner Building
  :double_sided: true
nwcb600a:
  :host: nwcb600a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Northwest Corner Building
  :double_sided: true
nwcb600b:
  :host: nwcb600b-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Northwest Corner Building
  :double_sided: true
schermerhorn601a:
  :host: schermerhorn601a-ninja.atg.columbia.edu
  :driver: HP LaserJet 4350 Series PS
  :location: Schermerhorn
  :double_sided: true
socialwork202a:
  :host: socialwork202a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4015
  :location: Social Work
  :double_sided: true
socialwork207a:
  :host: socialwork207a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4015
  :location: Social Work
  :double_sided: true
uris130a:
  :host: uris130a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Uris
  :double_sided: true
uris130b:
  :host: uris130b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Uris
  :double_sided: true
uris130c:
  :host: uris130c-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Uris
  :double_sided: true
uris130d:
  :host: uris130d-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 PS
  :location: Uris
  :double_sided: true
dodgeart412a:
  :host: dodgeart412a-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Dodge
  :double_sided: true
dodgeart412b:
  :host: dodgeart412b-ninja.atg.columbia.edu
  :driver: HP LaserJet P4515
  :location: Dodge
  :double_sided: true
socialwork105b:
  :host: socialwork105b-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 Series PS
  :location: Social Work
  :double_sided: true
socialwork105c:
  :host: socialwork105c-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 Series PS
  :location: Social Work
  :double_sided: true
socialwork105d:
  :host: socialwork105d-ninja.atg.columbia.edu
  :driver: HP LaserJet 9050 Series PS
  :location: Social Work
  :double_sided: true
socialwork105e:
  :host: socialwork105e-ninja.atg.columbia.edu
  :driver: HP LaserJet 9000 Series PS
  :location: Social Work
  :double_sided: true
socialwork214a:
  :host: socialwork214a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9000 Series PS
  :location: Social Work
  :double_sided: true
socialwork309a:
  :host: socialwork309a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9000 Series PS
  :location: Social Work
  :double_sided: true
socialwork401a:
  :host: socialwork401a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9000 Series PS
  :location: Social Work
  :double_sided: true
socialwork721a:
  :host: socialwork721a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9000 Series PS
  :location: Social Work
  :double_sided: true
socialwork821a:
  :host: socialwork821a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9000 Series PS
  :location: Social Work
  :double_sided: true
socialwork900a:
  :host: socialwork900a-ninja.atg.columbia.edu
  :driver: HP LaserJet 9000 Series PS
  :location: Social Work
  :double_sided: true
